[package]
name = "at51"
description = "Some applications for reverse engineering 8051 firmware"
readme = "README.md"
version = "0.1.1"
authors = ["8051Enthusiast"]
edition = "2018"
keywords = ["reverse-engineering", "8051"]
categories = ["command-line-utilities"]
license = "MIT"
travis-ci = { repository = "8051Enthusiast/at51", branc = "master" }
repository = "https://github.com/8051Enthusiast/at51"


[dependencies]
clap = "~2.33.0"
rustfft = "~3.0.0"
nom = "~5.0.0"
num-traits = "0.2"
num-derive = "0.2"
regex = "1"
lazy_static = "1.4.0"

[dev-dependencies]
hex = "~0.3.2"
